Repository UKHomeOffice/core-cloud-add-customer-action, pull requests merged in 2024-03, with the labels that each got.

#92 Update allowed OUs for isolated requirement
  badges/coverage.svg
  dist/index.js
  src/types.ts
Labels: minor

#90 LZA-93!: revert groups and identity center assignment changes
  .github/workflows/ci.yml
  __tests__/files/iam/empty.yaml
  __tests__/files/iam/expected.yaml
  __tests__/identitycenterassignment.test.ts
  __tests__/main.test.ts
  __tests__/terraform/files/groups/empty.yaml
  __tests__/terraform/files/groups/expected.yaml
  __tests__/terraform/files/groups/invalid.yaml
  __tests__/terraform/groups.test.ts
  __tests__/utils.ts
  badges/coverage.svg
  dist/index.js
  src/identitycenterassignment.ts
  src/main.ts
  src/terraform/groups.ts
  src/types/group.ts
Labels: major

#102 ci: update dependabot configuration
  .github/dependabot.yml
Labels: skip-release
